name: Gradle Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

steps:
  - uses: actions/checkout@v4

  - name: Read .sdkmanrc
    id: sdkmanrc
    run: |
      java_version=$(grep '^java=' .sdkmanrc | cut -d'=' -f2)
      echo "java-version=$java_version" >> $GITHUB_ENV

  - uses: actions/setup-java@v4
    with:
      distribution: 'graalvm'
      java-version: ${{ env.java-version }}

  - name: Grant execute permission for gradlew
    run: chmod +x gradlew

  - name: Build with Gradle
    run: ./gradlew build